l: 2.8498 # distance between car axle
laser:
  verbose: false
  window_width: 35.0
  window_length: 60.0
  threshold: 2.5
  iterations: 100
control:
  kpt: 0.1
  kit: 0.001
  kvt: 0.50
  krt: 0.20
  lin_vel: 1.5
  wait_time: 5.0
kalman:
  verbose: false
  # Elements of the process covariance matrix Q
  q00: 10.0 # variance of the angle between the car x-axis reference frame and the bisector line
           # i.e. the arctan(a), where a is the angular coefficient of the bisector line
  q11: 25.0 # variance of the linear coefficient of the bisector line with respect the reference frame of the car
  q22: 1.0 # variance of the car angular velocity
  q33: 25.0 # variance of the car linear velocity
  # Elements of the measurement covariance matrix R
  r00: 20.0
  r11: 100.0
  r22: 2.0
  r33: 10.0
topics:
  line_pcl: "bisector_pcl"
  filtered_line_pcl: "filtered_bisector_pcl"
  line_coeffs: "bisector_coeffs"
  filtered_line_coeffs: "filtered_bisector_coeffs"
  state_filter: "state_filter"
  points_ransac: "points_ransac"
  laser_scan: "scan"
  cmd_vel: "car_command"
  cmd_vel_twist: "cmd_vel"
tfs:
  base_link: "base_link"
  laser_link: "hokuyo_link"

